version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: store-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword200
      MYSQL_DATABASE: store
      MYSQL_USER: Delis
      MYSQL_PASSWORD: P@ssword200
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
